// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: pb/test.proto

package pb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uint32  uint32 `protobuf:"varint,1,opt,name=uint32,proto3" json:"uint32,omitempty"`
	Uint64  uint64 `protobuf:"varint,2,opt,name=uint64,proto3" json:"uint64,omitempty"`
	Bytes   []byte `protobuf:"bytes,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
	String_ string `protobuf:"bytes,4,opt,name=string,proto3" json:"string,omitempty"`
	Int32   int32  `protobuf:"varint,5,opt,name=int32,proto3" json:"int32,omitempty"`
	Int64   int64  `protobuf:"varint,6,opt,name=int64,proto3" json:"int64,omitempty"`
}

func (x *TestRecord) Reset() {
	*x = TestRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRecord) ProtoMessage() {}

func (x *TestRecord) ProtoReflect() protoreflect.Message {
	mi := &file_pb_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRecord.ProtoReflect.Descriptor instead.
func (*TestRecord) Descriptor() ([]byte, []int) {
	return file_pb_test_proto_rawDescGZIP(), []int{0}
}

func (x *TestRecord) GetUint32() uint32 {
	if x != nil {
		return x.Uint32
	}
	return 0
}

func (x *TestRecord) GetUint64() uint64 {
	if x != nil {
		return x.Uint64
	}
	return 0
}

func (x *TestRecord) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

func (x *TestRecord) GetString_() string {
	if x != nil {
		return x.String_
	}
	return ""
}

func (x *TestRecord) GetInt32() int32 {
	if x != nil {
		return x.Int32
	}
	return 0
}

func (x *TestRecord) GetInt64() int64 {
	if x != nil {
		return x.Int64
	}
	return 0
}

var File_pb_test_proto protoreflect.FileDescriptor

var file_pb_test_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x62, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x62, 0x22, 0x96, 0x01, 0x0a, 0x0a, 0x54, 0x65, 0x73,
	0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x69, 0x6e, 0x74, 0x33,
	0x32, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x75, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x69,
	0x6e, 0x74, 0x36, 0x34, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x6e, 0x74, 0x36,
	0x34, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_test_proto_rawDescOnce sync.Once
	file_pb_test_proto_rawDescData = file_pb_test_proto_rawDesc
)

func file_pb_test_proto_rawDescGZIP() []byte {
	file_pb_test_proto_rawDescOnce.Do(func() {
		file_pb_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_test_proto_rawDescData)
	})
	return file_pb_test_proto_rawDescData
}

var file_pb_test_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_test_proto_goTypes = []interface{}{
	(*TestRecord)(nil), // 0: test.pb.TestRecord
}
var file_pb_test_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_test_proto_init() }
func file_pb_test_proto_init() {
	if File_pb_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_test_proto_goTypes,
		DependencyIndexes: file_pb_test_proto_depIdxs,
		MessageInfos:      file_pb_test_proto_msgTypes,
	}.Build()
	File_pb_test_proto = out.File
	file_pb_test_proto_rawDesc = nil
	file_pb_test_proto_goTypes = nil
	file_pb_test_proto_depIdxs = nil
}
