package protoio

import (
	"github.com/gogo/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// isGoogleProtobufMsg checks if the given proto.Message was
// generated by the official Google protobuf compiler
func isGoogleProtobufMsg(msg proto.Message) bool {
	_, ok := msg.(interface {
		ProtoReflect() protoreflect.Message
	})
	return ok
}
